name = "optim/oada"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'optim/oada'"

[repository]
user = "optim"
project = "oada"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "optimfinance/aiken-common"
version = "0.1.0"
source = "github"
