name: Tests

on:
  push:
    branches: ["main", "staging"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      
      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix run .#aikenTests
      - name: OADA tests for ADA base asset
        run: nix run .#emulatorTests
      - name: OADA tests for non-ADA base asset
        run: nix run .#emulatorTests
        env:
          RANDOM_BASE_ASSET: 1
